
#@pubsubName=messagebus-csharp
@pubsubName=messagebus-node

# Publish to songs topic
POST http://localhost:3500/v1.0/publish/{{pubsubName}}/songs
Content-Type: application/json

{
    "id": 1,
    "artist": "Led Zeppelin",
    "name": "Communication Breakdown"
}
